### ISSUE TITLE
Match logger crashing

### ISSUE THREAD

**Issue by Raccok** [mdfwn/Dota2ProTracker#3]
I'm not sure yet what causes this, but the match logger is currently crashing when it fails to retrieve some data. See attached screenshot.

![matchlogger_crash](https://user-images.githubusercontent.com/18735093/30127089-4e199e4e-933e-11e7-885c-c380a2881288.png)

**Comment by mdfwn** [comment]
I fixed this error in particular with an earlier commit today. However, similar errors still occure when the API yields incomplete results, so the error handling overall needs to be more sophisticated.
